class RingProof:
    c_b: tuple
    c_accip: tuple
    c_accx: tuple
    c_accy: tuple
    px_zeta: tuple
    py_zeta: tuple
    s_zeta: tuple
    b_zeta: tuple
    accip_zeta: tuple
    accx_zeta: tuple
    accy_zeta: tuple
    c_q: tuple
    l_zeta_omega: tuple
    open_agg_zeta: tuple
    open_l_zeta_omega: tuple
