name: CI

on:
  push:
    branches: [master, main]
  pull_request:

jobs:
  lint-test:
    name: Lint & Test on ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install Hatch & dev deps
        run: |
          python -m pip install --upgrade pip hatch
          pip install -e .[dev]
          pip install -e ./dot_ring/curves[dev]
          pip install -e ./dot_ring/fiat_shamir[dev]
          pip install -e ./dot_ring/ring_proof[dev]
          pip install -e ./dot_ring/vrf[dev]

      - name: Run Ruff
        run: ruff check .

      - name: Run Black (check)
        run: black --check .

      - name: Run isort (check)
        run: isort --check-only .

      - name: Run tests
        run: pytest -q